from turtle import * 
import turtle as tur 

screen = Screen()
screen.setup(width = 1.0, height = 1.0)
canvas = screen.getcanvas()
root = canvas.winfo_toplevel()
root.overrideredirect(1)
tur.color("red")
tur.speed(6)
tur.begin_fill()
tur.pensize(3)
tur.left(50)
tur.forward(133)
tur.circle(50,200)
tur.right(140)
tur.circle(50,200)
tur.forward(133)
tur.end_fill()
tur.color("white")
tur.left(135)
tur.right(180)
tur.forward(200)
tur.right(90)
tur.forward(350)
tur.begin_fill()
tur.pensize(3)
tur.color("black")
write("Feliz dia do pai!", font=("Comic Sans MS", 100, "normal"))
delay(2000)
end_fill()
